// ============================================================================
// 2. LOCALIZATION (အများသုံးနိုင်အောင် loc အဖြစ် ပြင်ဆင်ထားသည်)
// ============================================================================
final Map<String, Map<String, String>> loc = {
  'en': {
    'student': 'Student', 'teacher': 'Teacher', 'owner': 'Owner', 'dashboard': 'Dashboard',
    'attendance': 'Attendance', 'tasks_done': 'Tasks', 'news': 'News', 'tasks': 'My Tasks',
    'complaint': 'Complain', 'complaints': 'Complaints', 'submit': 'Submit', 'title': 'Title',
    'desc': 'Description', 'cancel': 'Cancel', 'lang': 'MM', 'performance': 'Performance',
    'pending': 'Pending', 'progress': 'Progress', 'my_perf': 'My Performance',
    'assign_task': 'Assign Task', 'total_students': 'Students', 'total_teachers': 'Teachers',
    'school_overview': 'School Overview', 'all': 'All', 'target': 'Target',
    'create_announcement': 'Create Announcement', 'student_tasks': 'Student Tasks',
    'no_data': 'No data yet.', 'subject': 'Subject', 'due_date': 'Due Date',
    'submit_task': 'Submit Task', 'your_answer': 'Your Answer', 'submitted': 'Submitted',
    'not_submitted': 'Not Submitted', 'profile': 'Profile', 'logout': 'Logout',
    'class': 'Class', 'submissions': 'Submissions', 'grade_class': 'Grade',
    'change_lang': 'Language', 'attach_image': 'Attach Image', 'change_pic': 'Change Photo',
    'uploaded': 'Uploaded', 'login': 'Login', 'register': 'Register', 'welcome': 'Welcome',
    'create_account': 'Create Account', 'email': 'Email', 'password': 'Password', 'name': 'Name',
    'select_role': 'Select Role', 'no_account': "Don't have an account? Register",
    'have_account': 'Have an account? Login', 'login_success': 'Login Successful!',
    'register_success': 'Registered!', 'welcome_sub': 'Sign in to continue',
    'register_sub': 'Fill in your details', 'school_name': 'EduSchool',
    'pending_grading': 'To Grade', 'from': 'From', 'overdue': 'Overdue',
    'age': 'Age', 'location': 'Location', 'contact': 'Contact',
    'parent_name': "Parent", 'parent_phone': "Parent Phone",
    'save': 'Save', 'user_management': 'Users', 'edit_user': 'Edit User',
    'personal_info': 'Personal Info', 'student_info': 'Students', 'teacher_info': 'Teachers',
    'add_user': 'Add User', 'login_info': 'Login Info', 'basic_info': 'Basic Info',
    'role_info': 'Role Info', 'students': 'Students', 'teachers': 'Teachers',
    'grade': 'Grade', 'grades_taught': 'Teaches', 'users': 'users',
    'manage_by_grade': 'Manage by Grade', 'skills': 'Skills', 'experience': 'Experience',
    'leave_days': 'Leave Days', 'attendance_rate': 'Attendance', 'select_grade': 'Select Grade',
    'grade_required': 'Please select a grade', 'my_grade_tasks': 'My Grade Tasks',
    'nav_users': 'Users', 'quick_demo': 'Quick Demo Accounts', 'demo_hint': 'Use these to test the app',
    'welcome_back': 'Welcome Back', 'create_new': 'Create New Account',
  },
  'mm': {
    'student': 'ကျောင်းသား', 'teacher': 'ဆရာ/ဆရာမ', 'owner': 'ကျောင်းအုပ်', 'dashboard': 'ပင်မ',
    'attendance': 'တက်ရောက်မှု', 'tasks_done': 'တာဝန်', 'news': 'သတင်း', 'tasks': 'ကျွန်ုပ် တာဝန်များ',
    'complaint': 'တိုင်ကြား', 'complaints': 'တိုင်ကြားချက်များ', 'submit': 'ပေးပို့', 'title': 'ခေါင်းစဉ်',
    'desc': 'အကြောင်းအရာ', 'cancel': 'မလုပ်တော့', 'lang': 'EN', 'performance': 'အရည်အသွေး',
    'pending': 'စောင့်ဆိုင်း', 'progress': 'တိုးတက်မှု', 'my_perf': 'ကျွန်ုပ် အရည်အသွေး',
    'assign_task': 'တာဝန်ပေး', 'total_students': 'ကျောင်းသား', 'total_teachers': 'ဆရာ',
    'school_overview': 'ကျောင်း အခြေအနေ', 'all': 'အားလုံး', 'target': 'ပို့မည့်သူ',
    'create_announcement': 'သတင်းထုတ်', 'student_tasks': 'ကျောင်းသား တာဝန်များ',
    'no_data': 'ဒေတာ မရှိပါ။', 'subject': 'ဘာသာရပ်', 'due_date': 'နောက်ဆုံးရက်',
    'submit_task': 'တာဝန်ပို့', 'your_answer': 'အဖြေ', 'submitted': 'ပို့ပြီး',
    'not_submitted': 'မပို့ရသေး', 'profile': 'ပရိုဖိုင်', 'logout': 'ထွက်',
    'class': 'အတန်း', 'submissions': 'စစ်ရန်', 'grade_class': 'အတန်း',
    'change_lang': 'ဘာသာစကား', 'attach_image': 'ဓာတ်ပုံပူးတွဲ', 'change_pic': 'ပုံပြောင်း',
    'uploaded': 'တင်ပြီး', 'login': 'ဝင်ရောက်မည်', 'register': 'စာရင်းသွင်းမည်', 'welcome': 'ကြိုဆိုပါသည်',
    'create_account': 'အကောင့်ဖွင့်မည်', 'email': 'အီးမေးလ်', 'password': 'စကားဝှက်', 'name': 'အမည်',
    'select_role': 'အခန်းကဏ္ဍ ရွေးချယ်ပါ', 'no_account': 'အကောင့်မရှိဘူးလား? စာရင်းသွင်းပါ',
    'have_account': 'အကောင့်ရှိပြီးသားလား? ဝင်ရန်', 'login_success': 'အောင်မြင်စွာ ဝင်ရောက်ပြီး!',
    'register_success': 'အောင်မြင်စွာ စာရင်းသွင်းပြီး!', 'welcome_sub': 'ဆက်လက်လုပ်ဆောင်ရန် အကောင့်ဝင်ပါ',
    'register_sub': 'အချက်အလက်များ ပြည့်စုံစွာ ဖြည့်ပါ', 'school_name': 'EduSchool',
    'pending_grading': 'စစ်ရန်', 'from': 'မှ', 'overdue': 'နောက်ကျ',
    'age': 'အသက်', 'location': 'နေရပ်လိပ်စာ', 'contact': 'ဖုန်းနံပါတ်',
    'parent_name': 'မိဘအမည်', 'parent_phone': 'မိဘဖုန်းနံပါတ်',
    'save': 'သိမ်းမည်', 'user_management': 'အသုံးပြုသူများ', 'edit_user': 'ပြင်ဆင်မည်',
    'personal_info': 'ကိုယ်ရေးအချက်အလက်', 'student_info': 'ကျောင်းသားများ', 'teacher_info': 'ဆရာများ',
    'add_user': 'အသစ်ထည့်မည်', 'login_info': 'ဝင်ရောက်ရန် အချက်များ', 'basic_info': 'အခြေခံအချက်များ',
    'role_info': 'လုပ်ငန်းတာဝန်', 'students': 'ကျောင်းသား', 'teachers': 'ဆရာ',
    'grade': 'အတန်း', 'grades_taught': 'သင်ကြားသည့်အတန်း', 'users': 'ဦး',
    'manage_by_grade': 'အတန်းအလိုက် စီမံမည်', 'skills': 'ကျွမ်းကျင်မှု', 'experience': 'လုပ်သက်',
    'leave_days': 'ခွင့်ရက်', 'attendance_rate': 'တက်ရောက်မှု', 'select_grade': 'အတန်း ရွေးချယ်ပါ',
    'grade_required': 'ကျေးဇူးပြု၍ အတန်း ရွေးပေးပါ', 'my_grade_tasks': 'ကျွန်ုပ် အတန်း တာဝန်များ',
    'nav_users': 'အသုံးပြုသူ', 'quick_demo': 'စမ်းသပ်အကောင့်များ', 'demo_hint': 'ဒါတွေနဲ့ စမ်းသပ်နိုင်သည်',
    'welcome_back': 'ပြန်လည်ကြိုဆိုပါသည်', 'create_new': 'အကောင့်အသစ် ဖွင့်လှစ်မည်',
  }
};
